kind: pipeline
type: docker
name: Default
trigger:
  event:
  - pull_request

steps:
- name: Build Docker Image
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t odeanimate:drone-${DRONE_COMMIT} .

- name: Black
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
    - ./scripts/format.sh
  depends_on:
    - Build Docker Image

- name: PyLint
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
    - ./scripts/lint.sh
  depends_on:
    - Build Docker Image

- name: Tests
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
    - ./scripts/tests.sh
  depends_on:
    - Build Docker Image

- name: Code Verification
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
    - echo "Code Verification Complete"
  depends_on:
    - Black
    - PyLint
    - Tests

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: Publish
depends_on:
  - Default
trigger:
  branch: 
  - release
  event:
  - push

steps:
- name: Publish to PyPi
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
  - date


volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

