kind: pipeline
type: docker
name: Default
trigger:
  event:
  - push
  - pull_request

steps:
- name: Build Docker Image
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t odeanimate:drone-${DRONE_COMMIT} .

- name: Black
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
    - ./scripts/format.sh
  depends_on:
    - Build Docker Image

- name: PyLint
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
    - ./scripts/lint.sh
  depends_on:
    - Build Docker Image

- name: Tests
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
    - ./scripts/tests.sh
  depends_on:
    - Build Docker Image

- name: Code Verification
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
    - echo "Code Verification Complete"
  depends_on:
    - Black
    - PyLint
    - Tests

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: Publish
depends_on:
  - Default
trigger:
  branch: 
  - release
  event:
  - push

steps:
- name: Publish to PyPi
  image: odeanimate:drone-${DRONE_COMMIT}
  environment:
    PYPIRC:
      from_secret: PYPIRC
  commands:
  - date
  - echo "$PYPIRC" > ~/.pypirc
  - python -m build
  - twine upload --skip-existing --verbose dist/*
- name: git-push
  image: appleboy/drone-git-push
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
  settings:
    branch: release
    remote: "git@github.com:ekiim/odeanimate.git"
    ssh_key: ${SSH_KEY}

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

