kind: pipeline
type: docker
name: Default
trigger:
  event:
  - push
  - pull_request

steps:
- name: Build Docker Image
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t odeanimate:drone-${DRONE_COMMIT} -f ./scripts/Dockerfile .

- name: Black
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
    - ./scripts/format.sh
  depends_on:
    - Build Docker Image

- name: Tests
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
    - ./scripts/tests.sh
  depends_on:
    - Build Docker Image

- name: Documentation
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
    - ./scripts/build-docs.sh
  depends_on:
    - Build Docker Image

- name: Code Verification
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
    - echo "Code Verification Complete"
  depends_on:
    - Black
    - Tests
    - Documentation

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: Publish
depends_on:
  - Default
trigger:
  branch: 
  - release
  event:
  - push

steps:
- name: Publish to PyPi
  image: odeanimate:drone-${DRONE_COMMIT}
  environment:
    PYPI_TOKEN:
      from_secret: PYPI_TOKEN_FULL
  commands:
  - date
  - ./scripts/publish.sh

- name: Generate Documentation Site
  image: odeanimate:drone-${DRONE_COMMIT}
  commands:
  - date
  - ./scripts/build-docs.sh

- name: Deploy Documentation Site
  image: drillster/drone-rsync
  settings:
    hosts: [ "ekiim.xyz" ]
    user: ekiim
    source: /drone/src/site/.
    target: /var/www/xyz.ekiim.odeanimate
    recursive: true
    delete: true
    key:
      from_secret: ekiim-deployer-ssh

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

