site_name: odeanimate

nav:
- Home: index.md
- API: api/odeanimate.md 
- Examples: examples/index.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            members_order: source
            show_source: false
  - autorefs
  - mkdocs-jupyter:
      execute: True
      execute_ignore: "*.py"
      allow_errors: False
      include_source: True

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
  - yaml
  - python
