site_name: odeanimate
repo_name: 'ekiim/odeanimate'

nav:
- Home: index.md
- API: api/odeanimate.md 
- Examples: examples/index.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            members_order: source
            show_source: true
  - mknotebooks:
      execute: true
      timeout: 50
      allow_errors: true
      binder: true
      binder_service_name: "gh"
      binder_service_name: "gh"
      binder_branch: "master"

markdown_extensions:
  - def_list
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true


theme:
  name: "material"
